"use client";

import { useState } from "react";
import { api } from "@/lib/api";
import type { ScenarioResult } from "@/lib/types";

const ACTION_OPTIONS = [
  { value: "close_road_early:fac-hill-to-hill-bridge", label: "Close Hill-to-Hill Bridge earlier" },
  { value: "reposition_ambulance:fac-bethlehem-fire-1", label: "Reposition an ambulance ahead of impact" },
  { value: "add_secondary_route:fac-lvh-muhlenberg:fac-stlukes-bethlehem", label: "Add a secondary route between the two hospitals" },
];

/** Scenario Lab + Counterfactual Action Lab (sections 25-26), simple mode. */
export function ScenarioLabPanel() {
  const [severity, setSeverity] = useState("severe");
  const [durationHours, setDurationHours] = useState(6);
  const [selectedActions, setSelectedActions] = useState<string[]>([]);
  const [result, setResult] = useState<ScenarioResult | null>(null);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function toggleAction(value: string) {
    setSelectedActions((prev) => (prev.includes(value) ? prev.filter((a) => a !== value) : [...prev, value]));
  }

  async function handleRun() {
    setRunning(true);
    setError(null);
    try {
      const scenario = await api.createScenario({
        name: "Bethlehem flood scenario",
        mode: "simple",
        location_label: "Bethlehem, PA",
        hazard_type: "flood",
        severity,
        duration_hours: durationHours,
        time_of_day: "weekday_afternoon",
        river_condition: "already_elevated",
        actions: selectedActions,
      });
      const scenarioResult = await api.runScenario(scenario.scenario_id);
      setResult(scenarioResult);
    } catch {
      setError("Could not run the scenario. Check that the backend API is reachable.");
    } finally {
      setRunning(false);
    }
  }

  return (
    <div className="space-y-4 p-4">
      <div>
        <h2 className="text-sm font-semibold uppercase tracking-wide text-foreground/50">Scenario Lab</h2>
        <p className="mt-1 text-xs text-foreground/60">
          Simple mode - test a hazard scenario and response actions for the Bethlehem corridor. No number
          below is generated by a language model.
        </p>
      </div>

      <div className="space-y-2 text-sm">
        <label className="block">
          <span className="text-xs font-medium text-foreground/60">Severity</span>
          <select
            value={severity}
            onChange={(e) => setSeverity(e.target.value)}
            className="mt-0.5 w-full rounded-md border border-border bg-surface px-2 py-1.5"
          >
            <option value="watch">Watch</option>
            <option value="elevated">Elevated</option>
            <option value="severe">Severe</option>
            <option value="extreme">Extreme</option>
          </select>
        </label>
        <label className="block">
          <span className="text-xs font-medium text-foreground/60">Duration (hours)</span>
          <input
            type="number"
            min={1}
            max={48}
            value={durationHours}
            onChange={(e) => setDurationHours(Number(e.target.value))}
            className="mt-0.5 w-full rounded-md border border-border bg-surface px-2 py-1.5"
          />
        </label>
      </div>

      <div>
        <span className="text-xs font-medium text-foreground/60">Actions to test</span>
        <ul className="mt-1 space-y-1">
          {ACTION_OPTIONS.map((opt) => (
            <li key={opt.value}>
              <label className="flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={selectedActions.includes(opt.value)}
                  onChange={() => toggleAction(opt.value)}
                />
                {opt.label}
              </label>
            </li>
          ))}
        </ul>
      </div>

      <button
        type="button"
        onClick={handleRun}
        disabled={running}
        className="w-full rounded-md bg-accent px-3 py-2 text-sm font-medium text-white hover:opacity-90 disabled:opacity-50"
      >
        {running ? "Running…" : "Run scenario"}
      </button>

      {error && <p className="text-sm text-status-severe">{error}</p>}

      {result && (
        <div className="space-y-3 border-t border-border pt-3">
          <h3 className="text-xs font-semibold uppercase tracking-wide text-foreground/50">Results</h3>
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs text-foreground/50">
                <th className="pb-1">Metric</th>
                <th className="pb-1">Before</th>
                <th className="pb-1">After</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="py-0.5">Affected population (est.)</td>
                <td>{result.baseline.affected_population_estimate.toLocaleString()}</td>
                <td>{result.with_actions.affected_population_estimate.toLocaleString()}</td>
              </tr>
              <tr>
                <td className="py-0.5">Best travel time</td>
                <td>{result.baseline.best_travel_time_minutes ?? "-"} min</td>
                <td>{result.with_actions.best_travel_time_minutes ?? "-"} min</td>
              </tr>
              <tr>
                <td className="py-0.5">Emergency response time</td>
                <td>{result.baseline.estimated_emergency_response_minutes} min</td>
                <td>{result.with_actions.estimated_emergency_response_minutes} min</td>
              </tr>
            </tbody>
          </table>
          <p className="text-xs text-foreground/70">
            Estimated cost of tested actions: ${result.delta.estimated_cost_usd.toLocaleString()}
          </p>
          <div>
            <h4 className="text-xs font-semibold text-foreground/50">Assumptions</h4>
            <ul className="mt-1 list-inside list-disc text-xs text-foreground/60">
              {result.assumptions.map((a, i) => (
                <li key={i}>{a}</li>
              ))}
            </ul>
          </div>
          <div>
            <h4 className="text-xs font-semibold text-foreground/50">Remaining uncertainty</h4>
            <ul className="mt-1 list-inside list-disc text-xs text-foreground/60">
              {result.uncertainty_notes.map((a, i) => (
                <li key={i}>{a}</li>
              ))}
            </ul>
          </div>
        </div>
      )}
    </div>
  );
}
