"""AI/model output schemas: nowcasting steps, analogs, scenarios, annotations."""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

from app.schemas.common import EvidenceTrail, ModelBasis, TimeRange
from app.schemas.enums import Confidence


class ImpactStep(BaseModel):
    """One step of 'What may happen next' (section 11)."""

    step_id: str
    order: int
    statement: str = Field(description="Plain language, e.g. 'Water may reach a low-lying road'")
    time_window: TimeRange
    confidence: Confidence
    evidence_trail: EvidenceTrail


class ImpactSequence(BaseModel):
    incident_id: str
    title: str
    observed_signals: list[str]
    steps: list[ImpactStep]
    overall_confidence: Confidence
    model_basis: ModelBasis
    disclaimer: str = (
        "This is an AI-supported estimate that combines official forecasts and "
        "observations. It does not replace official warnings."
    )


class HistoricalAnalog(BaseModel):
    analog_id: str
    event_name: str
    year: int
    similarity_score: float = Field(ge=0.0, le=1.0)
    similarity_features: list[str]
    what_happened_next: str
    key_differences: list[str]
    why_it_may_not_repeat: list[str]
    data_quality: Confidence
    source_url: Optional[str] = None


class ModelInference(BaseModel):
    inference_id: str
    model_basis: ModelBasis
    output_summary: str
    evidence_trail: EvidenceTrail


class Scenario(BaseModel):
    scenario_id: str
    name: str
    created_at: datetime
    mode: str = Field(description='"simple" or "advanced"')
    location_label: str
    center: tuple[float, float]
    hazard_type: str
    severity: str
    duration_hours: float
    time_of_day: str
    river_condition: Optional[str] = None
    advanced_params: dict[str, float | str] = Field(default_factory=dict)
    actions: list[str] = Field(
        default_factory=list,
        description="Counterfactual actions under test, e.g. 'close_road_early:seg-12'",
    )


class ScenarioResult(BaseModel):
    scenario_id: str
    computed_at: datetime
    baseline: dict
    with_actions: dict
    delta: dict
    assumptions: list[str]
    uncertainty_notes: list[str]
    method: str = (
        "Deterministic graph/routing computation (NetworkX + rule-based hazard overlay). "
        "No numeric outcome in this result was generated by a language model."
    )


class UserAnnotation(BaseModel):
    annotation_id: str
    incident_id: Optional[str] = None
    author: str
    created_at: datetime
    text: str
    geometry: Optional[dict] = None
