"use client";
import { useEffect,useMemo,useState } from "react";
import { AlertTriangle,CalendarDays,CheckCircle2,Database,FlaskConical,Play,Radio,Search } from "lucide-react";
import { api } from "@/lib/api";
import type { AnalysisHazard,AnalysisLocation,AnalysisMode,AnalysisRunResult,HazardEventSearchResponse } from "@/lib/types";
const MODES:Array<{id:Exclude<AnalysisMode,"demo">;label:string}>=[{id:"live",label:"Live event"},{id:"historical",label:"Historical event"},{id:"hypothetical",label:"Hypothetical / return period"}];
const HAZARDS:Array<{id:AnalysisHazard;label:string}>=[{id:"hurricane",label:"Tropical cyclone"},{id:"earthquake",label:"Earthquake"},{id:"flood",label:"Flood"},{id:"wildfire",label:"Wildfire"}];
const PROGRESS=["Loading event","Processing hazard footprint","Finding affected locations","Loading structures","Loading Census context","Applying vulnerability","Finalizing audit manifest"];
type Props={location:AnalysisLocation|null;onRequestLocation:()=>void;onDemo:()=>Promise<void>;onResult:(result:AnalysisRunResult)=>void;onNotice:(message:string)=>void};
export function ModelBuilder({location,onRequestLocation,onDemo,onResult,onNotice}:Props){
 const [mode,setMode]=useState<Exclude<AnalysisMode,"demo">>("hypothetical"),[hazard,setHazard]=useState<AnalysisHazard>("flood"),[catalog,setCatalog]=useState<HazardEventSearchResponse|null>(null),[eventId,setEventId]=useState(""),[threshold,setThreshold]=useState("MMI IV+"),[returnPeriod,setReturnPeriod]=useState(100),[startDate,setStartDate]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[endDate,setEndDate]=useState(()=>new Date().toISOString().slice(0,10)),[loadingEvents,setLoadingEvents]=useState(false),[running,setRunning]=useState(false),[stage,setStage]=useState(0);
 useEffect(()=>{if(mode==="hypothetical")return;let cancelled=false;void api.hazardEvents(mode,hazard,startDate,endDate).then(r=>{if(!cancelled)setCatalog(r)}).catch(()=>{if(!cancelled)setCatalog({events:[],provider:"Unavailable",retrieved_at:new Date().toISOString(),data_status:"unavailable",message:"The authoritative catalog could not be loaded. No substitute event was used."})}).finally(()=>{if(!cancelled)setLoadingEvents(false)});return()=>{cancelled=true}},[mode,hazard,startDate,endDate]);
 function changeMode(next:Exclude<AnalysisMode,"demo">){setMode(next);setEventId("");setCatalog(null);setLoadingEvents(next!=="hypothetical")}
 function changeHazard(next:AnalysisHazard){setHazard(next);setEventId("");setCatalog(null);setLoadingEvents(mode!=="hypothetical");setThreshold(next==="earthquake"?"MMI IV+":next==="hurricane"?"Any official watch or warning":next==="flood"?"Authoritative inundation footprint":"Authoritative fire perimeter")}
 const selectedEvent=catalog?.events.find(x=>x.provider_event_id===eventId);const valid=useMemo(()=>mode==="hypothetical"?hazard==="flood"&&Boolean(location)&&[50,100,500].includes(returnPeriod):Boolean(eventId),[eventId,hazard,location,mode,returnPeriod]);
 async function run(){if(!valid)return;setRunning(true);setStage(0);const timer=window.setInterval(()=>setStage(v=>Math.min(v+1,PROGRESS.length-1)),650);try{const result=await api.runAnalysis({mode,hazard_type:hazard,location,provider:selectedEvent?.provider,event_id:eventId||null,advisory_id:selectedEvent?.advisory_id,threshold:mode==="hypothetical"?`${returnPeriod}-year / ${100/returnPeriod}% AEP`:threshold,return_period_years:mode==="hypothetical"?returnPeriod:null,start_date:mode==="historical"?startDate:null,end_date:mode==="historical"?endDate:null,vulnerability_model:null,simulation_count:1000,seed:12345});onResult(result)}catch{onNotice("The analysis service failed. No result or replacement values were invented.")}finally{window.clearInterval(timer);setRunning(false)}}
 return <section className="floating-card scenario-card workflow-card">
  <div className="card-heading"><div><span className="eyebrow">Traceable analysis</span><h2>Build a risk scenario</h2></div><button className="sample-link" type="button" onClick={()=>void onDemo()}><FlaskConical size={14}/>Use sample demonstration</button></div>
  <fieldset className="mode-selector"><legend>Analysis mode</legend><div>{MODES.map(item=><button type="button" key={item.id} className={mode===item.id?"selected":""} onClick={()=>changeMode(item.id)}>{item.id==="live"?<Radio size={14}/>:item.id==="historical"?<CalendarDays size={14}/>:<FlaskConical size={14}/>} {item.label}</button>)}</div></fieldset>
  <label>1 · Hazard type<select value={hazard} onChange={e=>changeHazard(e.target.value as AnalysisHazard)}>{HAZARDS.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
  {mode==="historical"&&<div className="date-fields"><label>2 · Start date<input type="date" value={startDate} onChange={e=>{setStartDate(e.target.value);setEventId("");setCatalog(null);setLoadingEvents(true)}}/></label><label>End date<input type="date" value={endDate} min={startDate} onChange={e=>{setEndDate(e.target.value);setEventId("");setCatalog(null);setLoadingEvents(true)}}/></label></div>}
  {mode!=="hypothetical"&&<><label>{mode==="live"?"2 · Active event":"3 · Historical event"}<select value={eventId} disabled={loadingEvents} onChange={e=>setEventId(e.target.value)}><option value="">{loadingEvents?"Loading authoritative catalog…":"Select an event"}</option>{catalog?.events.map(x=><option key={x.provider_event_id} value={x.provider_event_id}>{x.name}</option>)}</select></label>{catalog?.message&&<div className="workflow-message"><AlertTriangle size={15}/><span>{catalog.message}</span></div>}{selectedEvent&&<div className="event-provenance"><strong>{selectedEvent.provider} · {selectedEvent.classification}</strong><span>Updated {selectedEvent.update_time?new Date(selectedEvent.update_time).toLocaleString():"not reported"}</span><span>{selectedEvent.footprint_available?"Usable footprint advertised":"Impact footprint not available"}</span></div>}<label>{mode==="live"?"3 · Impact threshold":"4 · Event threshold"}<select value={threshold} onChange={e=>setThreshold(e.target.value)}>{hazard==="earthquake"&&<><option>MMI IV+</option><option>MMI VI+</option><option>MMI VII+</option><option>MMI VIII+</option></>}{hazard==="hurricane"&&<><option>Any official watch or warning</option><option>At least 5% probability of 34-knot winds</option><option>At least 5% probability of 50-knot winds</option><option>At least 1% probability of 64-knot winds</option><option>Available surge/inundation footprint</option></>}{hazard==="flood"&&<option>Authoritative inundation footprint</option>}{hazard==="wildfire"&&<option>Authoritative fire perimeter</option>}</select></label></>}
  {mode==="hypothetical"&&<><label>2 · Location<button className="location-picker" type="button" onClick={onRequestLocation}><Search size={14}/>{location?location.name:"Search and select a U.S. location"}</button></label>{location&&<div className="geography-proof"><CheckCircle2 size={15}/><span><strong>{location.county??"County not available"}</strong>{location.tract?`${location.tract} · GEOID ${location.tract_geoid}`:"Census tract not available"}</span></div>}<label>3 · Scenario type<select><option>FEMA effective flood-hazard area</option></select></label><label>4 · Return period<select value={returnPeriod} onChange={e=>setReturnPeriod(Number(e.target.value))}><option value={50}>50-year flood — 2% annual exceedance probability</option><option value={100}>100-year flood — 1% annual exceedance probability</option><option value={500}>500-year flood — 0.2% annual exceedance probability</option></select></label></>}
  <label>{mode==="hypothetical"?"5":"6"} · Exposure<select><option>USACE National Structure Inventory 2026 Base</option></select></label><label>{mode==="hypothetical"?"6":"7"} · Vulnerability<select disabled><option>Applied only when compatible asset intensity exists</option></select></label>
  <div className="assumption-note"><Database size={16}/><span><strong>Validity gate</strong> If defensible asset-level intensity is missing, RiskChain returns exposure screening—not a dollar-loss estimate.</span></div>{running&&<div className="run-progress">{PROGRESS.map((x,i)=><span key={x} className={i<=stage?"active":""}><i/>{x}</span>)}</div>}<button className="primary run-button" type="button" disabled={!valid||running} onClick={()=>void run()}><Play size={17} fill="currentColor"/>{running?PROGRESS[stage]:valid?"Run risk analysis":mode==="hypothetical"?"Select a supported location and scenario":"Select an authoritative event"}</button>
 </section>
}
