"""Build a date-specific view from official forecast products only."""

from __future__ import annotations

from datetime import datetime, timezone

from app.adapters.base import AdapterResponse
from app.adapters.nhc import NHCForecastPoint, NHCForecastTrack
from app.schemas.enums import DataStatus
from app.schemas.future_outlook import FutureForecastEvent, FutureOutlookResponse

MAX_OFFICIAL_TRACK_HOURS = 120


def build_future_outlook(
    target_at: datetime,
    tracks_response: AdapterResponse[NHCForecastTrack],
    *,
    now: datetime | None = None,
) -> FutureOutlookResponse:
    """Return forecast records only where a source supplies a valid track.

    The target may be far in the future; in that case the response is a useful,
    explicit unavailable state rather than a fabricated planning event.
    """
    now = now or datetime.now(timezone.utc)
    target_at = target_at.astimezone(timezone.utc) if target_at.tzinfo else target_at.replace(tzinfo=timezone.utc)
    horizon_hours = (target_at - now).total_seconds() / 3600

    if horizon_hours <= 0:
        return _unavailable(target_at, horizon_hours, now, "Choose a future UTC date. Current observations are available in the live event view.")
    if horizon_hours > MAX_OFFICIAL_TRACK_HOURS:
        return _unavailable(
            target_at,
            horizon_hours,
            now,
            "No authoritative event forecast is connected that far ahead. EarthPulse does not extrapolate beyond published five-day NHC advisory tracks.",
        )
    if tracks_response.status == DataStatus.UNAVAILABLE:
        return FutureOutlookResponse(
            target_at=target_at,
            horizon_hours=round(horizon_hours, 1),
            availability="unavailable",
            availability_label="Official forecast feed unavailable",
            availability_detail=tracks_response.note or "The NHC feed could not be reached, so no substitute future events are shown.",
            generated_at=now,
            data_status=DataStatus.UNAVAILABLE,
            error=tracks_response.note,
        )

    events: list[FutureForecastEvent] = []
    for track in tracks_response.items:
        point = _nearest_eligible_point(track.points, target_at)
        events.append(
            FutureForecastEvent(
                event_id=track.event_id,
                name=track.name,
                storm_type=track.storm_type,
                basin=track.basin,
                headline=track.headline,
                observed_at=track.observed_at,
                coverage_status="dated_track_point" if point and track.valid_from and track.valid_to else "official_advisory",
                forecast_valid_from=track.valid_from if point and track.valid_from else None,
                forecast_valid_to=track.valid_to if point and track.valid_to else None,
                selected_point_at=point.valid_at if point and track.valid_from and track.valid_to else None,
                selected_point_center=point.center if point and track.valid_from and track.valid_to else None,
                advisory_url=track.advisory_url,
                track_url=track.track_url,
            )
        )

    if not events:
        return FutureOutlookResponse(
            target_at=target_at,
            horizon_hours=round(horizon_hours, 1),
            availability="available",
            availability_label="No official event track for this date",
            availability_detail="The supported NHC forecast products were checked. No active named tropical cyclone has a published forecast point covering this date.",
            generated_at=now,
            data_status=tracks_response.status,
        )
    return FutureOutlookResponse(
        target_at=target_at,
        horizon_hours=round(horizon_hours, 1),
        availability="available",
        availability_label=f"{len(events)} official forecast track{'s' if len(events) != 1 else ''} available",
        availability_detail="Showing NHC advisory products within the supported horizon. A map position appears only when the source supplies a dated forecast point; otherwise the official advisory is shown without an inferred position. No future event has been generated by EarthPulse.",
        generated_at=now,
        data_status=tracks_response.status,
        items=events,
    )


def _nearest_eligible_point(points: list[NHCForecastPoint], target_at: datetime) -> NHCForecastPoint | None:
    if not points or target_at < points[0].valid_at or target_at > points[-1].valid_at:
        return None
    return min(points, key=lambda point: abs((point.valid_at - target_at).total_seconds()))


def _unavailable(target_at: datetime, horizon_hours: float, now: datetime, detail: str) -> FutureOutlookResponse:
    return FutureOutlookResponse(
        target_at=target_at,
        horizon_hours=round(horizon_hours, 1),
        availability="unavailable",
        availability_label="Forecast coverage unavailable",
        availability_detail=detail,
        generated_at=now,
        data_status=DataStatus.UNAVAILABLE,
    )
